# Generated by Django 6.0.6 on 2026-06-13 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(help_text='16-digit Rwandan National ID', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be exactly 16 digits and contain only numbers.', regex='^\\d{16}$')])),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(help_text='Primary phone linked to Irembo profile', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Rwandan mobile format (e.g., 0788XXXXXX or +250788XXXXXX).', regex='^(?:\\+250|0)7[2389]\\d{7}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('category_or_provisional', models.CharField(help_text='Target category (e.g., B) or existing provisional number for upgrades', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Slot Check'), ('PROCESSING', 'Filling Form on Irembo'), ('AWAITING_OTP', 'Awaiting OTP Input'), ('SUCCESS', 'Registration Completed Successfully'), ('FAILED', 'Process Failed/Aborted')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('EXPIRED', 'Payment Code Expired')], default='UNPAID', max_length=20)),
                ('otp_code', models.CharField(blank=True, max_length=10, null=True)),
                ('billing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('application_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Application',
                'verbose_name_plural': 'Client Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='automation__status_9439ff_idx'), models.Index(fields=['national_id'], name='automation__nationa_5e14bb_idx')],
            },
        ),
    ]
