# Generated by Django 5.0.14 on 2026-06-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapplication',
            name='category_or_provisional',
            field=models.CharField(help_text='Target category (e.g., B) or existing provisional number', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Slot Check'), ('PROCESSING', 'Filling Form on Irembo'), ('AWAITING_OTP', 'Awaiting OTP Input'), ('OTP_PROVIDED', 'OTP Provided, Finalizing'), ('SUCCESS', 'Registration Completed Successfully'), ('FAILED', 'Process Failed/Aborted'), ('CANCELED', 'Process Canceled by User')], default='PENDING', max_length=20),
        ),
    ]
