# Generated by Django 6.0.6 on 2026-06-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0002_alter_clientapplication_category_or_provisional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientapplication',
            name='category_or_provisional',
        ),
        migrations.AddField(
            model_name='clientapplication',
            name='category',
            field=models.CharField(default='B', help_text='Target driving category selection (e.g., A, B, B2, C1, D)', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientapplication',
            name='provisional_number',
            field=models.CharField(blank=True, help_text='Provisional license string. Required for new Definitive applications; leave blank for Category Upgrades.', max_length=50, null=True),
        ),
    ]
