# Generated by Django 6.0.6 on 2026-06-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0003_remove_clientapplication_category_or_provisional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientapplication',
            name='otp_code',
        ),
        migrations.AlterField(
            model_name='clientapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Slot Check'), ('PROCESSING', 'Filling Form on Irembo'), ('FINALIZING', 'Slot Secured — Submitting Application'), ('SUCCESS', 'Registration Completed Successfully'), ('FAILED', 'Process Failed/Aborted'), ('CANCELED', 'Process Canceled by User'), ('MANUAL_REVIEW_NEEDED', 'Manual Review Required')], default='PENDING', max_length=20),
        ),
    ]
