# Generated by Django 6.0.6 on 2026-06-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0006_clientapplication_log_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplication',
            name='user_response',
            field=models.CharField(blank=True, help_text='Temporary field for user interaction during process', max_length=50, null=True),
        ),
    ]
