# Generated by Django 6.0.6 on 2026-06-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0010_applicationrunhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Application Created'), ('EDIT', 'Application Updated'), ('DELETE', 'Application Deleted'), ('BULK', 'Bulk Action'), ('ENGINE', 'Automation Engine')], max_length=20)),
                ('description', models.TextField()),
                ('application_name', models.CharField(blank=True, max_length=255, null=True)),
                ('application_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Activity Log',
                'verbose_name_plural': 'System Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
