# Generated by Django 6.0.6 on 2026-08-02 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0011_systemactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text="Teacher's contact phone number", max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='clientapplication',
            name='district',
            field=models.CharField(blank=True, default='Kicukiro', help_text='Akarere (District)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientapplication',
            name='exam_date',
            field=models.DateField(blank=True, help_text='Itariki (Date)', null=True),
        ),
        migrations.AddField(
            model_name='clientapplication',
            name='exam_time',
            field=models.CharField(blank=True, help_text='Igihe (Time)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientapplication',
            name='working_site',
            field=models.CharField(blank=True, help_text='Aho ikizamini kizabera (Working site - Kicukiro only)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientapplication',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='From Teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='automation_app.teacher'),
        ),
    ]
