# Generated by Django 6.0.6 on 2026-08-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0012_teacher_clientapplication_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplication',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='True if application is archived (hidden from active dashboard box)'),
        ),
        migrations.AddIndex(
            model_name='clientapplication',
            index=models.Index(fields=['is_archived'], name='automation__is_arch_4686e7_idx'),
        ),
    ]
